// front_angular/src/app/app.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./sass/main.scss']
})
export class AppComponent {
  title = 'voip';
}

 <!-- <app-login class="login"></app-login> -->
<!--<app-dashboard></app-dashboard>-->

<router-outlet></router-outlet>

// front_end/voip/src/App.vue
<template>
  <div id="app">
    <Login></Login>
  </div>
</template>

<script>
import Login from "./components/Login.vue";
import DashBoard from "./components/DashBoard.vue";


export default {
  name: "app",
  components: {
    Login,
    DashBoard
  }
};
</script>


<style lang="scss">
@import "./sass/main.scss";
</style>
