// front_angular/src/app/app.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./sass/main.scss']
})
export class AppComponent {
  title = 'voip';
}

 <!-- <app-login class="login"></app-login> -->
<!--<app-dashboard></app-dashboard>-->

<router-outlet></router-outlet>

// front_vue/vue-voip/src/App.vue
<template>
  <div id="app">
    <header>
      <!-- <div id="nav">
        <router-link to="/">Login</router-link>
        <router-link to="/dashboard">Dashboard</router-link>
      </div> -->
    </header>
    <router-view />
  </div>
</template>

/* Los estilos se propagan de manera global */
<style lang="scss" src="./sass/main.scss"></style>
